name: Build & test
on: [push]
jobs:
  build-test:
    defaults:
      run:
        working-directory: nextjs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Check formatting
        run: yarn run prettier -c .

      - name: Build for production
        run: yarn build

      - name: Install playwright
        run: yarn run playwright install

      - name: Build container
        run: docker build -t sshcontainer ./ssh_container
        working-directory: ./

      - name: Run container
        run: docker run -d -p 5555:22 sshcontainer

      - name: Check running containers
        run: docker ps

      - name: Test with playwright
        run: yarn test
